name: semana_info_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

  # FontAwasome
  font_awesome_flutter: ^8.8.1

    #Ligar, mapa etc
  url_launcher: ^5.5.0

  #Lancher icons
  flutter_launcher_icons: "^0.7.3"

  #Usar ScopedModel
  scoped_model: ^1.0.1

  group_button: ^3.1.0

  # Firebase 
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.16
  firebase_messaging: ^6.0.16
  firebase_in_app_messaging: ^0.1.2
  firebase_auth: any
  google_sign_in: any
  firebase_storage: any

  # pegar informacoes do dispositivo
  device_info: ^0.4.2+6

  #Usar Imagens transparente
  transparent_image: ^1.0.0

  flutter_staggered_grid_view: "^0.2.2"


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/img/


#executar esse comando quando alterar
#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android:  true #"launcher_icon"
  ios: true
  image_path: "icons/icon.jpg"